export { IndentationType, IConfiguration, IConfigurationRequest, IContext, IFileSystem, IContextFeatures, LanguageId, ConfigurationNamespace, TypeAnalyzerStrategy, DefaultFileExtensions } from './types';
export { activate as activateAutocomplete } from './features/autocomplete';
export { activate as activateColor } from './features/color';
export { activate as activateDefinition } from './features/definition';
export { activate as activateDiagnostic } from './features/diagnostic';
export { activate as activateFormatter } from './features/formatter';
export { activate as activateHover } from './features/hover';
export { activate as activateSignature } from './features/signature';
export { activate as activateSubscriptions } from './features/subscriptions';
export { activate as activateSymbol } from './features/symbol';
export { activate as activateSemantic } from './features/semantic';
export { activate as activateFoldingRange } from './features/folding-range';
export * as ASTScraper from './helper/ast-scraper';
export { ActiveDocument, DocumentManager } from './helper/document-manager';
export { DocumentMerger } from './helper/document-merger';
export { LookupHelper } from './helper/lookup-type';
export { MarkdownString } from './helper/markdown-string';
export { createHover, createSignatureInfo, createTooltipHeader, formatDefaultValue, formatTypes, appendTooltipBody, appendTooltipHeader } from './helper/tooltip';
export { default as typeAnalyzer } from './helper/type-manager';
export { lookupIdentifier, lookupBase } from './helper/ast-utils';
export { semanticTokensLegend, buildTokens } from './helper/semantic-token-builder';
export { CoreContext } from './context';