export { IndentationType, IConfiguration, IContext, IFileSystem, IContextFeatures, LanguageId, ConfigurationNamespace } from './types';
export { activate as activateAutocomplete } from './features/autocomplete';
export { activate as activateColor } from './features/color';
export { activate as activateDefinition } from './features/definition';
export { activate as activateDiagnostic } from './features/diagnostic';
export { activate as activateFormatter } from './features/formatter';
export { activate as activateHover } from './features/hover';
export { activate as activateSignature } from './features/signature';
export { activate as activateSubscriptions } from './features/subscriptions';
export { activate as activateSymbol } from './features/symbol';
export * as ASTScraper from './helper/ast-scraper';
export { ActiveDocument, DocumentManager } from './helper/document-manager';
export { LookupHelper } from './helper/lookup-type';
export { MarkdownString } from './helper/markdown-string';
export { createHover, createSignatureInfo, createTooltipHeader, formatDefaultValue, formatTypes, appendTooltipBody, appendTooltipHeader } from './helper/tooltip';
export { lookupIdentifier, lookupBase, default as typeAnalyzer } from './helper/type-manager';
export { CoreContext } from './context';